name: Blender

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  ROC_ENABLE_PRE_VEGA: 1

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        git clone https://projects.blender.org/blender/blender.git
        cd blender
        make update
        make
        ls -r ..
    # - name: Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     files: |
