name: Blender

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  ROC_ENABLE_PRE_VEGA: 1

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install VS Components
      uses: thepwrtank18/install-vs-components@v1.0.0
      with:
        components: Microsoft.VisualStudio.Workload.NativeDesktop
    - name: Build
      shell: cmd
      run: |
        git clone https://projects.blender.org/blender/blender.git
        cd blender
        make update
        make release
        dir ..
