name: Blender

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  ROC_ENABLE_PRE_VEGA: 1

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      shell: cmd
      run: |
        git clone -b blender-v4.3-release https://projects.blender.org/blender/blender.git
        cd blender
        make update
        make release
        dir ..
